- name: Install the latest version of nginx
  ansible.builtin.dnf:
    name: nginx
    state: latest

- name: Copy expense.conf file
  ansible.builtin.template:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf
    mode: '0644'  # optional but good practice
    owner: root
    group: root

- name: App Prerequisites
  ansible.builtin.include_role:
    name: common
    tasks_from: app_prereq

- name: Start and enable Nginx service
  ansible.builtin.systemd:
    name: nginx
    enabled: true
    state: restarted
