format_version: 10
pipelines:
  deploy:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      ansible:
        git: https://github.com/Tejaswini-Devops/expense-ansible
        branch: main
    stages:
      - dev:
          fetch_materials: true
          approval:
            type: success
            allow_only_on_success: false
          jobs:
            deployment:
              timeout: 0
              tasks:
                - exec:
                    command: ls
                      - -l
                      - -A
