- name: Setup Hostname
  ansible.builtin.shell: set-hostname {{env}}-{{component}}

- name: Download node_exporter setup file
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v{{node_exporter_version}}/node_exporter-{{node_exporter_version}}.linux-amd64.tar.gz
    dest: /opt
    remote_src: yes

- name: copy node_exporter service file from template
  ansible.builtin.template:
    src: node_exporter.service
    dest: /etc/systemd/system/node_exporter.service


- name: Start node_exporter service
  ansible.builtin.systemd_service:
    name: node_exporter
    state: restarted
    enabled: yes
    daemon-reload: yes

- name: Copy Elastic Repo file
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: Install Filebeat
  ansible.builtin.dnf:
    name: filebeat
    state: installed

- name: Filebeat config update
  ansible.builtin.template:
    src: filebeat.yml
    dest: /etc/filebeat/filebeat.yml

- name: Start Filebeat
  ansible.builtin.systemd_service:
    name: filebeat
    state: restarted


- name: Configure rysyslog # is a program where we can write all the logs coming from backend or frontend components put in the respective logs either frontend or backend whatever
  ansible.builtin.template:
    src: rsyslog.conf
    dest: /etc/rsyslog.conf/{{component}}.conf

- name: reStart rsyslog
  ansible.builtin.systemd_service:
    name: rsyslog
    state: restarted

